# VISA Interview Training System Configuration

# API keys and endpoints
mistral:
  api_key: "" # Set via environment variable MISTRAL_API_KEY
  api_url: "https://api.mistral.ai/v1/chat/completions"
  model: "mistral-large-latest"

groq_whisper:
  api_key: "" # Set via environment variable GROQ_API_KEY
  model : "whisper-large-v3-turbo"
  endpoint: "https://api.groq.com/openai/v1/audio/transcriptions"

# TTS Configuration
edge_tts:
  output_dir: "audio_output"
  default_voice: "en-US-AriaNeural"
  audio_format: "mp3"
  rate: "+0%"
  volume: "+0%"
  voice_options:
    - "en-US-AriaNeural"
    - "en-US-GuyNeural"
    - "en-GB-SoniaNeural"
    - "en-AU-NatashaNeural"

# RAG Configuration
rag:
  persist_directory: "data/chroma_db"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 1000
  chunk_overlap: 0

# Answer Processing
answers:
  max_duration_sec: 60
  silence_threshold: 300
  min_answer_length: 10

# Subscription Tiers
subscription:
  free:
    max_questions: 5
    feature_set: "basic"
  super:
    max_questions: 10
    feature_set: "standard"
  premium:
    max_questions: 15
    feature_set: "advanced"
